# This is a basic workflow to help you get started with Actions

name: Dispatcher

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [apply, destroy]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Payload value: ${{ toJSON(github.event.client_payload) }}"
      - name: apply changes
        if: github.event.type == 'apply'
        run: echo "====== Applying Changes to ${{ github.event.client_payload.environment }}! ========"
      - name: destroying changes
        if: github.event.type == 'destroy'
        run: echo "====== Destroying Changes to ${{ github.event.client_payload.environment }}! ========"
